/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ReadingsNotary, ReadingsNotaryInterface } from "./ReadingsNotary";
export { ReadingsNotary__factory } from "./ReadingsNotary__factory";
