/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type {
  IdentityManager,
  IdentityManagerInterface,
} from "./IdentityManager";
export type { ReadingsNotary, ReadingsNotaryInterface } from "./ReadingsNotary";
export { IdentityManager__factory } from "./IdentityManager__factory";
export { ReadingsNotary__factory } from "./ReadingsNotary__factory";
