/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides, Signer, utils } from "ethers";
import type { ReadingsNotary, ReadingsNotaryInterface } from "./ReadingsNotary";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "NewMeterReading",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101c8806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b374012b14610030575b600080fd5b61004a600480360381019061004591906100f5565b61004c565b005b818160405161005c92919061015f565b60405180910390203373ffffffffffffffffffffffffffffffffffffffff167f6d503e29b2082d55217ca5b7e581b11b55140b7414799715f654e8a02526ed7a60405160405180910390a35050565b60008083601f8401126100bd57600080fd5b8235905067ffffffffffffffff8111156100d657600080fd5b6020830191508360018202830111156100ee57600080fd5b9250929050565b6000806020838503121561010857600080fd5b600083013567ffffffffffffffff81111561012257600080fd5b61012e858286016100ab565b92509250509250929050565b60006101468385610178565b9350610153838584610183565b82840190509392505050565b600061016c82848661013a565b91508190509392505050565b600081905092915050565b8281833760008383015250505056fea264697066735822122008e807cc817d849f10e2bf2ff8c4a6e651635d00bb8a5e79d6f90692542603ea64736f6c63430008040033";

export class ReadingsNotary__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ReadingsNotary> {
    return super.deploy(overrides || {}) as Promise<ReadingsNotary>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ReadingsNotary {
    return super.attach(address) as ReadingsNotary;
  }
  connect(signer: Signer): ReadingsNotary__factory {
    return super.connect(signer) as ReadingsNotary__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReadingsNotaryInterface {
    return new utils.Interface(_abi) as ReadingsNotaryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): ReadingsNotary {
    return new Contract(address, _abi, signerOrProvider) as ReadingsNotary;
  }
}
