name: Docker CI

on:
  push:
    branches: [master]
    paths:
      - "aggregator/**"
      - "der/**"
      - "docker/**"
      - "prosumer/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker aggregator image
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ./aggregator
          push: true
          tags: tendto/ew-der-api:aggregator

      - name: Docker prosumer image
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ./prosumer
          push: true
          tags: tendto/ew-der-api:prosumer

      - name: Docker der image
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ./der
          push: true
          tags: tendto/ew-der-api:der
